clase Excepciones

  metodo metodo_que_lanza_error
    error "ups!"
  fin

  metodo metodo_que_lanza_excepcion
    lanzar nuevo MiExcepcion("foo")
  fin
  
//  
//  metodo metodo_que_captura_excepcion
//    intentar
//      error ""
//    capturar//(excepcion)
//      //hacer algo..
//      lanzar 1//excepcion
//    fin
//  fin
 
fin

excepcion MiExcepcion
fin


